name: Test a23

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test-a23.yml'

jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - env:
          V: ${{ secrets.KS_A23 }}
        run: echo "ascii 23 byte nhan duoc ${#V} ky tu"
