name: Test t128

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test-t128.yml'

jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - env:
          V: ${{ secrets.KS_T128 }}
        run: echo "label: random 128 byte nhan duoc ${#V} ky tu"
