name: Test ascii256

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test-ascii256.yml'

jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - env:
          V: ${{ secrets.KS_ASCII256 }}
        run: echo "label: ascii 256 byte nhan duoc ${#V} ky tu"
