name: Test S1024

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test-s1024.yml'

jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - env:
          V: `${{ secrets.KS_S1024 }}`
        run: echo "nhan duoc 1024 byte"
