name: Test t192

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test-t192.yml'

jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - env:
          V: ${{ secrets.KS_T192 }}
        run: echo "label: random 192 byte nhan duoc ${#V} ky tu"
